---
title: cee.
author: Larry Zheng
vignette: >
  %\VignetteIndexEntry{cee.}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(lubridate)
```

## R Markdown

```{r read_csvs}
processed <- read_csv("/cloud/project/data/raw_data/gonio_aux_merge.csv")
processed
cee <- read_csv(file = "/cloud/project/data/raw_data/ATLANTIC-BRS_CEE Metadata.csv") %>%
  mutate(date_time = as.POSIXct(paste(Date, as.character(CEE.Times)), format = "%m/%d/%y %H:%M:%S"))
cee
series <- read_csv("/cloud/project/data/raw_data/All_Series.csv") %>%
  mutate(date_time = as.POSIXct(paste(Day, as.character(Time)), format = "%d-%B-%Y %H:%M:%S"))
series
```

Loop
```{r}
cee_names <- c("cee19_01", "cee19_02", "cee19_03", "cee19_04")
name_index <- 1

for (i in seq(from = 1, to = length(cee), by = 2)) {
  cee_start <- cee$date_time[i]
  cee_end <- cee$date_time[i+1]
  animals <- strsplit(cee$Focal.animals[i], " ")
  animals <- unlist(animals)
  
  assign(cee_names[name_index], cee_function(cee_start, cee_end, animals))
  name_index <- name_index + 1
}

#paste("cee19_0", as.character(i),sep="")
```
