---
title: Locations and Deployment Locations Intersection.
author: Larry Zheng
vignette: >
  %\VignetteIndexEntry{Locations and Deployment Locations Intersection.}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(lubridate)
```

## R Markdown



```{r cars}
locations <- read_csv("/cloud/project/BRSPackage/inst/extdata/raw_data/All_Locations.csv")
deploy <- read_csv("/cloud/project/BRSPackage/inst/extdata/raw_data/2019_SatTag_DeployLocations.csv")
```

```{r}
deploy$SatTag_ID = substr(deploy$SatTag_ID,1,nchar(deploy$SatTag_ID)-5)
deploy
```

```{r deploy-make-datetime}
deploy <- deploy %>%
  mutate(date_time = as.POSIXct(paste(date, " ", as.character(TimeOn)), format = "%d-%B-%y %H:%M:%S"))
deploy
```


```{r}
# Add column of when tag was put on the individual
tag_on_tib <- deploy[match(locations$DeployID, deploy$SatTag_ID),27]
tag_on_vec <- pull(tag_on_tib, date_time)

locations$tag_on <- tag_on_vec
# Subset: [rows, columns]. 27th column is datetime of when tag on

locations <- locations %>%
  mutate(date_time = as.POSIXct(Date, format = "%H:%M:%S %d-%B-%Y"))
# Use B for month format because months are written out, not in decimal format
locations
```

```{r}
# Remove observations where Date is before tag was on
processed_locations <- locations %>%
  filter(date_time >= tag_on)

processed_locations

# The locations that were removed (we don't save this data frame)
removed_locations <- locations %>%
  filter(date_time < tag_on)
removed_locations
```


