---
title: cee.
author: Larry Zheng
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(lubridate)
```

## R Markdown

```{r read_csvs}
processed <- read_csv("/cloud/project/data/raw_data/gonio_aux_merge.csv")
processed
cee <- read_csv(file = "/cloud/project/data/raw_data/ATLANTIC-BRS_CEE Metadata.csv") %>%
  mutate(date_time = as.POSIXct(paste(Date, as.character(CEE.Times)), format = "%m/%d/%y %H:%M:%S"))
cee
series <- read_csv("/cloud/project/data/raw_data/All_Series.csv") %>%
  mutate(date_time = as.POSIXct(paste(Day, as.character(Time)), format = "%d-%B-%Y %H:%M:%S"))
series
```


```{r}
cee19_01 <- processed %>%
  group_by(DeployID) %>%
  summarize(start_date = range(date_time)[1],
            end_date = range(date_time)[2])
cee19_01 <- cee19_01 %>%
  mutate(date_range = end_date - start_date)
cee19_01 <- cee19_01 %>%
  mutate(date_range = as.integer(date_range))
cee19_01 <- cee19_01 %>%
  mutate(average_locs = nrow(cee19_01)/date_range)
series_cee19_01 <- series %>%
  group_by(DeployID) %>%
  summarize(series_start_date = range(date_time)[1],
            series_end_date = range(date_time)[2])
series_cee19_01 <- series_cee19_01 %>%
  mutate(series_date_range = series_end_date - series_start_date)
cee19_01
series_cee19_01
total <- merge(cee19_01, series_cee19_01, by= "DeployID")
total
```


Larry's chunk
```{r}
cee19_01 <- processed %>%
  group_by(DeployID) %>%
  summarize(start_date = range(date_time)[1],
            end_date = range(date_time)[2]
            ) %>% 
  mutate(date_range = end_date - start_date)

cee19_01
```


Larry's chunk draft
```{r}
cee19_01 <- processed %>%
  group_by(DeployID) %>%
  mutate(
         num_satellite = case_when(startsWith(Source, "locations") ~ n()),
         num_aux = case_when(startsWith(Source, "aux") ~ n()),
         num_gonio = case_when(startsWith(Source, "gonio") ~ n())
         )
  summarize(start_date = range(date_time)[1],
            end_date = range(date_time)[2]
            ) %>% 
  mutate(date_range = end_date - start_date
         )

cee19_01
```


```{r}
cee19_01 <- data.frame(DeployID=character(),
                 Start.Date.Locs=as.Date(character()), 
                 End.Date.Locs=as.Date(character()), 
                 Length.Locs=integer(),
                 Avg.Locs.Per.Day=double(),
                 Num.Data.Points.Locs=integer(),
                 Num.Satellite=integer(),
                 Num.Aux=integer(),
                 Num.Locs.Before.CEE=integer(),
                 Num.Locs.After.CEE=integer(),
                 Start.Date.Series=as.Date(character()), 
                 End.Date.Series=as.Date(character()), 
                 Length.Series=integer(),
                 Num.Data.Points.Series=integer(),
                 Num.Series.Before.CEE=integer(),
                 Num.Series.After.CEE=integer(),
                 stringsAsFactors=TRUE) 
```

```{r}
deploy_ids_tib <- cee[1, "Focal.animals"]
deploy_ids <- deploy_ids_tib  %>%
  pull(Focal.animals) %>%
  str_split("  ")

deploy_ids <- as.vector(unlist(deploy_ids, use.names=FALSE))


cee19_01 <- data.frame(deploy_ids,
                 stringsAsFactors=TRUE) 

```

Vector Initializations
```{r}
len <- length(deploy_ids)

Start.Date.Locs <- rep(now(), length = len)
End.Date.Locs <- rep(now(), length = len)
Length.Locs <- rep(NA, length = len)
Num.Data.Points.Locs <- vector(length = len)
Num.Satellite <- vector(length = len)
Num.Aux <- vector(length = len)
Num.Locs.Before.CEE <- vector(length = len)
Num.Locs.After.CEE <- vector(length = len)
Start.Date.Series <- rep(now(), length = len)
End.Date.Series <- rep(now(), length = len)
Length.Series <- rep(NA, length = len)
Num.Data.Points.Series <- vector(length = len)
Num.Series.Before.CEE <- vector(length = len)
Num.Series.After.CEE <- vector(length = len)
```



Test of the loop
```{r}
individual_locs <- locations %>%
    filter(DeployID == deploy_ids[1])

Start.Date.Locs[1] <- as.POSIXct(first(individual_locs$Date),  format = "%H:%M:%S %d-%B-%Y")

# Start.Date.Locs <- c(Start.Date.Locs, as.POSIXct(first(individual_locs$Date),  format = "%H:%M:%S %d-%B-%Y"))
End.Date.Locs[1] <- as.POSIXct(last(individual_locs$Date),  format = "%H:%M:%S %d-%B-%Y")
Length.Locs[1] <- (End.Date.Locs[1] - Start.Date.Locs[1])

Num.Data.Points.Locs[1] <- nrow(individual_locs)
# Num.Satellite <- vector(length = len)
# Num.Aux <- vector(length = len)

# For before and after: make two subsetted dataframes of locations filtered by datetime before and after cee

locs_before_count <- individual_locs %>%
  filter(Date < )

# Num.Locs.Before.CEE <- vector(length = len)
# Num.Locs.After.CEE <- vector(length = len)
```


Loop
``{r}
for (i in length(deploy_ids)) {
  individual_locs <- locations %>%
    filter(DeployID = deploy_ids[i])
}
```